# Generated by Django 4.1.5 on 2023-01-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.TextField(default='')),
                ('stack_info', models.CharField(default='', max_length=200)),
                ('category', models.CharField(max_length=50, null=True)),
                ('company_link', models.TextField(default='')),
                ('company_recruit_link', models.TextField(default='')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default=None)),
                ('img_url', models.TextField(default=None)),
                ('title', models.CharField(default=None, max_length=200)),
                ('teacher', models.CharField(default='', max_length=100)),
                ('headline', models.TextField(default='')),
                ('level', models.CharField(default='', max_length=30)),
                ('score', models.FloatField(default=0, null=True)),
                ('course_time', models.CharField(default='', max_length=100)),
                ('student_cnt', models.IntegerField(default=0, null=True)),
                ('recommend', models.IntegerField(default=0, null=True)),
                ('review_cnt', models.IntegerField(default=0, null=True)),
                ('price', models.IntegerField(default='', null=True)),
                ('rank', models.FloatField(default=None, null=True)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.TextField(default='')),
                ('assort', models.CharField(default='', max_length=50)),
                ('described', models.TextField()),
            ],
            options={
                'db_table': 'Stack',
            },
        ),
        migrations.CreateModel(
            name='Stack_Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(max_length=20)),
                ('stack_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.stack')),
            ],
            options={
                'db_table': 'Stack_Dict',
            },
        ),
        migrations.CreateModel(
            name='Related_Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_stack', models.CharField(max_length=50)),
                ('related_stack_logo', models.TextField(default='')),
                ('related_stack_pk', models.IntegerField(default=0)),
                ('stack_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.stack')),
            ],
            options={
                'db_table': 'Related_Stack',
            },
        ),
        migrations.CreateModel(
            name='Course_Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.stack')),
            ],
            options={
                'db_table': 'Course_Stack',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='stack',
            field=models.ManyToManyField(through='course.Course_Stack', to='course.stack'),
        ),
        migrations.CreateModel(
            name='Company_Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.company')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.stack')),
            ],
            options={
                'db_table': 'Company_Stack',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='stack',
            field=models.ManyToManyField(through='course.Company_Stack', to='course.stack'),
        ),
    ]
