# Generated by Django 4.1.5 on 2023-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sentiment',
            field=models.FloatField(default=0, null=True),
        ),
    ]
