# Generated by Django 4.1.5 on 2023-01-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(default='', max_length=200),
        ),
    ]
